### ISSUE TITLE
Publish robot encoders and Cartesian pose

### ISSUE THREAD

**Issue by xEnVrE** [robotology-playground/yarp-omega3#1]
As per the title.

**Comment by traversaro** [comment]
Just FYI, are you aware of https://github.com/robotology/haptic-devices and https://github.com/robotology/yarp/blob/0fcdd28793d2b8d2356c72a2edb728774a9ef7a3/src/libYARP_dev/src/yarp/dev/IHapticDevice.h#L29 ?

**Comment by xEnVrE** [comment]
@traversaro, I wasn't aware of it. Thank you!

Howerver, in the case of this repository I also need to send Cartesian poses to the robot and this seems not included to the public API of `IHapticDevice`. Or am I missing something?

**Comment by traversaro** [comment]
> However, in the case of this repository I also need to send Cartesian poses to the robot and this seems not included in the public API of `IHapticDevice`. Or am I missing something?

Yes, that it is possible, I just wanted to let you know that there was something related, probably the network wrapper server and client can also be extended to cover slightly different interfaces.
